trading:
  pair_symbol: "BTCUSDT"
  fiat_symbol: "USD"
  crypto_symbol: "BTC"
  my_truncate: 5
  protection:
    sl_level: 0.02
    tp1_level: 0.1
    sl_amount: 1
    tp1_amount: 1
  buy_ready: true
  sell_ready: true
  bench_mode: true
  backtest: true
  risk_level: "Max"
  capital: 100
  cible: 200000
  temps: 5
  dca: 100