trading:
  backtest: true
  bench_mode: true
  buy_ready: true
  capital: 1000
  cible: 200000
  crypto_symbol: BTC
  dca: 100
  fiat_symbol: USD
  my_truncate: 5
  pair_symbol: BTCUSDT
  protection:
    sl_amount: 1
    sl_level: 0.02
    tp1_amount: 1
    tp1_level: 0.1
  risk_level: Max
  sell_ready: true
  temps: 5
